### ISSUE TITLE
Mehrere Termine an einem Tag auswählbar?

### ISSUE THREAD

**Issue by planepix** [trilobit-gmbh/contao-databaseformfieldoptions-bundle#10]
Hallo Peter,

kann man mit diesem Bundle durch Anpassung des Templates? erreichen, das man auch unterschiedliche Termine an einem Tag auswählen kann?

Aktuell versuche ich die Events ins Formular einzubinden; habe am gleichen Tag um 10 und um 11 Uhr ein Event.
Ausgegeben wird zwei mal das Datum. Prima wäre wenn man auch die definierte Uhrzeit und somit das Event eindeutig auswählen kann.

Lässt sich das mit Anpassung des Templates erreichen?

Danke und Grüße
Thomas

**Comment by planepix** [comment]
Ich habs glaub schon hinbekommen :-)

```
<?php if ('option' == $option['type']): ?>
        <option value="<?= $option['value'] ?>"<?= $option['selected'] ?>><?= \Contao\Date::parse('d.m.Y H:i', $option['label']); ?></option>
      <?php endif; ?>
```

**Comment by trilobit-gmbh** [comment]
;-)
