### ISSUE TITLE
Ausgabe eines bestimmten Zeitraums in "WHERE" ?

### ISSUE THREAD

**Issue by sfx12** [trilobit-gmbh/contao-databaseformfieldoptions-bundle#6]
Hallo!

erstmal "TOP EXTENSION" .. leider schaffe ich es nicht mir die AUsgabe für einen bestimmten Zeitraum nur auszugeben!

Ich möchte z.B. nur zukünftige EInträge der nächsten 3 Monate anzeigen lassen,

mit `DATE_SUB(CURDATE(), INTERVAL +3 MONTH) AND CURDATE()` klappt es nicht oder auch `startDate BETWEEN DATE_ADD(CURDATE(), INTERVAL +3 MONTH) AND CURDATE()` auch leider nicht!

Ich hoffe Ihr könnt helfen!

Vielen Dank - bleibt gesund!

**Comment by sfx12** [comment]
ich kann dir auch einen zugang geben !? an welche email ?

**Comment by trilobit-gmbh** [comment]
Lass mal mit Zugangsdaten ;-) Ich schaue mir das zeitnah an und melde mich. Versprechen kann und will ich aber nichts ;-)

**Comment by sfx12** [comment]
Ok :-) Aber schonmal vielen Dank für deine Zeit! Bleib Gesund.

**Comment by trilobit-gmbh** [comment]
Hallo @sfx12,

ich habe mir Deine Frage an einer Demo angeschaut; es geht ;-)

Diese Seite von MySQL ist die Referenz zu Deiner Frage:
https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_date-add

Dein Ansatz ging schon gut in die richtige Richtung. Ich habe im Bspl die News-Tabelle hergenommen.
Tabelle: `tl_news`
Option: `id`
Bezeichnung: `headline`
keine Gruppierung
WHERE: `date > UNIX_TIMESTAMP(DATE_ADD(CURDATE(),INTERVAL -1 MONTH))`
Keine Order

Die Datum in den News werden als Timestamp abgespeichert; also musst Du dem Where sagen, dass es ein Timestamp sein soll (`UNIX_TIMESTAMP`).
Über das `DATE_ADD` kannst Du dann die Zeiträume definieren.
Hier im Beispiel vom aktuellen Tag der letzte Monat ausgewählt (bzw bis 12 Uhr)

1) Konfiguration
![2021-05-26-17-21-darc-a11 trilobit home](https://user-images.githubusercontent.com/7868402/119687078-310fb300-be47-11eb-9346-879a1d3cf1c9.png)

2) "kompletter" Inhalt Archiv
![2021-05-26-17-22-darc-a11 trilobit home](https://user-images.githubusercontent.com/7868402/119687098-366cfd80-be47-11eb-8bee-4a16b2044964.png)

3) Select Ergebnis
![2021-05-26-17-23-darc-a11 trilobit home](https://user-images.githubusercontent.com/7868402/119687113-3bca4800-be47-11eb-99c7-af7b136d48b0.png)

**Comment by trilobit-gmbh** [comment]
Wenn Dir das Bundle gefällt und ich Dir helfen konnte; vielleicht möchtest Du uns/mir ja eine Pizza sponsern ;-)

Am Einfachsten geht das über ein PayPal-Spendenformular auf unserer Homepage; z.B. hier (https://www.trilobit.de/trilobits/constants-ein-contao-bundle.html) am Seitenende ;-)

Liebe Grüße
Peter Adelmann, trilobit GmbH

**Comment by sfx12** [comment]
Vielen Dank...kam noch nicht dazu es zu testen, aber die Doku schonmal mega von dir...vielen Dank.PS..kleine Spende ging raus.Am 26.05.2021 17:28 schrieb trilobit-gmbh ***@***.***>:

Wenn Dir das Bundle gefällt und ich Dir helfen konnte; vielleicht möchtest Du uns/mir ja eine Pizza sponsern ;-)

Am Einfachsten geht das über ein PayPal-Spendenformular auf unserer Homepage; z.B. hier (https://www.trilobit.de/trilobits/constants-ein-contao-bundle.html) am Seitenende ;-)

Liebe Grüße

Peter Adelmann, trilobit GmbH

**Comment by sfx12** [comment]
Hallo, ich habe das nun probiert, mir tl_calender_events scheints das wohl nicht so zu funken.. bekomme einen sql error laut log:

`request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\SyntaxErrorException: "An exception occurred while executing 'SELECT DISTINCT id,title FROM tl_calendar_events WHERE pid=1 AND date > UNIX_TIMESTAMP(DATE_ADD(CURDATE(),INTERVAL -1MONTH))':  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 1" at /var/customers/webs/id0/mo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 98 {"exception":"[object] (Doctrine\\DBAL\\Exception\\SyntaxErrorException(code: 0): An exception occurred while executing 'SELECT DISTINCT id,title FROM tl_calendar_events WHERE pid=1 AND date > UNIX_TIMESTAMP(DATE_ADD(CURDATE(),INTERVAL -1MONTH))':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 1 at /var/customers/webs/id0/mo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:98, Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 1 at /var/customers/webs/id0/mo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18, PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 1 at /var/customers/webs/id0/mo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:132)"} []`

habe es so eingetragen: pid=1 AND date > UNIX_TIMESTAMP(DATE_ADD(CURDATE(),INTERVAL -1MONTH))

screenshot:
[https://www.dropbox.com/s/6bs13nxw2n9f5zg/Screenshot%202021-06-17%20at%2010-39-20%20Formulare.png?dl=0](url)

**Comment by trilobit-gmbh** [comment]
Warum soll das nicht mit den Events gehen? ;-)

Hier hat das SQL einen Syntaxfehler in dem Bereich, der als "Filter" im Backend eingetragen ist.

Ich denke, dass es an den Fehlenden Leerzeichen liegt; vgl mein Muster:
`date > UNIX_TIMESTAMP(DATE_ADD(CURDATE(),INTERVAL -1 MONTH))`
Bei dir fehlt das Leerzeichen zwischen -1 und MONTH
`date > UNIX_TIMESTAMP(DATE_ADD(CURDATE(),INTERVAL -1MONTH))`

Steht auch in der Fehlermeldung wo der Fehler auftritt ;-)

Bitte noch einmal schauen ;-) Gerne Feedback.

**Comment by sfx12** [comment]
Hallo nochmals,

yieppie es geht 

hab mal mein Hirn etwas eingeschaltet... also so funzt es optimal startDate> UNIX_TIMESTAMP(DATE_ADD(CURDATE(),INTERVAL -1 MONTH))

nur hätte ich im selectfeld gerne das man als erstes ein leeres feld hat mit z.B. “wähle dein Event” das mach ich im backend...jedoch schmeisst er mir das an unterste stelle + nur den value und kein label !?

Trotzallem VIELEN DANK FÜR DEINE MÜHE & ZEIT!!!

LG SFX12
