### ISSUE TITLE
PHP8 / Contao 4.13 LTS

### ISSUE THREAD

**Issue by trilobit-gmbh** [trilobit-gmbh/contao-databaseformfieldoptions-bundle#9]

**Comment by philvdb** [comment]
siehe https://github.com/trilobit-gmbh/contao-databaseformfieldoptions-bundle/pull/8 - ich fange jetzt an das Bundle in einem 4.13-Projekt zu verwenden, werde berichten, wenn es Probleme gibt.

**Comment by planepix** [comment]
Feedback: Unter Contao 4.13.6 klemmt es mit PHP 8.0 und 8.1. PHP 7.4 klappt.

**Comment by trilobit-gmbh** [comment]
see 1.1.0

**Comment by planepix** [comment]
Danke Peter. Mit 8.0 und 8.1 bei netcup und Contao 4.13.6 getestet
